version: "3.9"

services:
  db:
    #   Используем официальные postgis-image
    image: postgis/postgis:11-3.0-alpine
    restart: on-failure
    #   Насадил новую базу на старую дату
    #   P.S. Всегда стоит делать волюм у базы, чтобы
    #     не потерять все данные при перебилдивании
    #   Для кастомной папки с данными задаем в prod.env
    #     переменную PGDATA=/var/lib/postgres/data/pgdata
    volumes:
      - /usr/local/var/postgres:/var/lib/postgres/data/pgdata
    environment:
      - POSTGRES_DB=hello_django_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    expose:
      - 5432
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db