version: "3"

services:
  db:
    #   Используем официальные postgis-image
    image: postgis/postgis:11-3.0-alpine
    restart: on-failure
    #   Насадил новую базу на старую дату
    #   P.S. Всегда стоит делать волюм у базы, чтобы
    #     не потерять все данные при перебилдивании
    #   Для кастомной папки с данными задаем в prod.env
    #     переменную PGDATA=/var/lib/postgres/data/pgdata
    volumes:
      - ./db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=eco_patrol_db
      - POSTGRES_USER=admin_user
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432
    expose:
      - 5432
  api:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - photo:/api_locator/photos
    ports:
      - "8000:8000"
    restart: on-failure
    expose:
      - 8000
    depends_on:
      - db

  web:
    build: ./frontend
    stdin_open: true
    command: [ "npm" ,"start" ]
    volumes:
      - ./frontend:/api_locator/frontend
      - node-modules:/api_locator/frontend/node_modules
    ports:
      - "3000:3000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    restart: on-failure
    depends_on:
      - api
      - web

volumes:
  node-modules:
  photo: